<?php

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;


class EventsTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
       DB::table('events')->insert([
            [
              'event_type_id' => '2',
              'title' => 'ZDHC & Sustainability Implementation in Textile Industry',
              'details' => 'In a world where people are struggling every moment to sustain in the current status they are living, the fashion and apparel industry, on which millions of peoples are directly dependent have some responsibilities to the society and its’ elements. Stakeholders like the governments, brands and buyers, consumer right protectors, labor right protectors, community right protectors, trade associations, financial institutions and the factories have their own perspective of sustainability. A holistic approach towards sustainability is needed considering all counterparts and stakeholders to put some real positive impact on businesses, people and planet. Factories being the core and one of the most impactful stakeholders in the value chain need to take systematic approach for implementing sustainability.',
              'venue' => 'Lotus Lounge, Uttara Club, House – 6, Road – 11, Sector – 1',
              'webinar_url' => null,
              'room_id' => null,
              'password' => null,
              'start_date' => '2020-08-07',
              'end_date' => '2020-08-07',
              'start_time' => '05:30:00',
              'end_time' => '09:30:00 ',
              'contact_phone_no' => '018888888888',
              'contact_email' => 'ttn@textiletoday.com',
              'logo' => 'over-img.jpg',
              'banner' => 'cover-img.jpg',
              'total_flag' => '0',
              'is_featured' => '0',
              'is_public' => '0',
              'status' => '0',
              'total_views' => '1',
              'total_likes' => '10',
              'total_comments' => '0',
            ],
            [
              'event_type_id' => '2',
              'title' => 'Hightex 2020',
              'details' => 'Heart of world technical textiles and nonwoven sector will beat at HIGHTEX 2020.',
              'venue' => 'Lotus Lounge, Uttara Club, House – 6, Road – 11, Sector – 1',
              'webinar_url' => null,
              'room_id' => null,
              'password' => null,
              'start_date' => '2020-06-02',
              'end_date' => '2020-06-06',
              'start_time' => '00:00:00',
              'end_time' => '00:00:00 ',
              'contact_phone_no' => '+90 212 876 75 06',
              'contact_email' => ' info@teknikfuarcilik.com',
              'logo' => 'over-img.jpg',
              'banner' => 'cover-img.jpg',
              'total_flag' => '0',
              'is_featured' => '0',
              'is_public' => '0',
              'status' => '0',
              'total_views' => '1',
              'total_likes' => '10',
              'total_comments' => '0',
            ],
            [
                'event_type_id' => '2',
              'title' => 'CAMBODIA’S LEADING B2B EVENTS & TRADE SHOW.',
              'details' => 'CAMBODIA’S LEADING B2B EVENTS & TRADE SHOW.',
              'venue' => 'Diamond Island Convention & Exhibition Center ,',
              'webinar_url' => null,
              'room_id' => null,
              'password' => null,
              'start_date' => '2020-08-01',
              'end_date' => '2020-08-30',
              'start_time' => '00:00:00',
              'end_time' => '00:00:00 ',
              'contact_phone_no' => '+886-2-26596000',
              'contact_email' => 'akai@chanchao.com.tw',
              'logo' => 'over-img.jpg',
              'banner' => 'cover-img.jpg',
              'total_flag' => '0',
              'is_featured' => '0',
              'is_public' => '0',
              'status' => '0',
              'total_views' => '1',
              'total_likes' => '10',
              'total_comments' => '0',
            ],
            [
              'event_type_id' => '3',
              'title' => 'Dhaka Intl Textile & Garment Machinery Exhibition',
              'details' => 'Information, Inspirations and Opportunities.Cambodia Intl Textile & Apparel Accessories Exhibition',
              'venue' => 'International Convention City Bashundhara (ICCB',
              'webinar_url' => null,
              'room_id' => null,
              'password' => null,
              'start_date' => '2020-06-11',
              'end_date' => '2020-06-14',
              'start_time' => '09:00:00',
              'end_time' => '05:00:00 ',
              'contact_phone_no' => '+886-2-26596000',
              'contact_email' => 'akai@chanchao.com.tw',
              'logo' => 'over-img.jpg',
              'banner' => 'cover-img.jpg',
              'total_flag' => '0',
              'is_featured' => '0',
              'is_public' => '0',
              'status' => '0',
              'total_views' => '1',
              'total_likes' => '10',
              'total_comments' => '0',
            ],
            [
               'event_type_id' => '3',
              'title' => 'BANGLADESH’S LEADING B2B EVENTS & TRADE SHOW',
              'details' => 'Information, Inspirations and Opportunities.',
              'venue' => ' International Convention City Bashundhara (ICCB)',
              'webinar_url' => null,
              'room_id' => null,
              'password' => null,
              'start_date' => '2020-12-18',
              'end_date' => '2020-12-21',
              'start_time' => '00:00:00',
              'end_time' => '00:00:00 ',
              'contact_phone_no' => '+886-2-26596000',
              'contact_email' => 'akai@chanchao.com.tw',
              'logo' => 'over-img.jpg',
              'banner' => 'cover-img.jpg',
              'total_flag' => '0',
              'is_featured' => '0',
              'is_public' => '0',
              'status' => '0',
              'total_views' => '1',
              'total_likes' => '10',
              'total_comments' => '0',
            ],
            [
              'event_type_id' => '3',
              'title' => 'MYANMAR’S LEADING B2B EVENTS & TRADE SHOW',
              'details' => 'The only dedicated industry specific international trade show for Plastics, Printing & Packaging Industry in Myanmar.The Best sourcing hub in Myanmar for Electrical, Electronics & Electric Power Equipment and related Trade Fair',
              'venue' => 'Saigon Exhibition & Conference Center (SECC) (799 Nguyen Van Linh Parkway, Tan Phu Ward, District 7, Ho Chi Minh City, Vietnam)',
              'webinar_url' => null,
              'room_id' => null,
              'password' => null,
              'start_date' => '2020-09-23',
              'end_date' => '2020-09-26',
              'start_time' => '09:00:00',
              'end_time' => '05:00:00 ',
              'contact_phone_no' => '+886-2-26596000',
              'contact_email' => 'akai@chanchao.com.tw',
              'logo' => 'over-img.jpg',
              'banner' => 'cover-img.jpg',
              'total_flag' => '0',
              'is_featured' => '0',
              'is_public' => '0',
              'status' => '0',
              'total_views' => '1',
              'total_likes' => '10',
              'total_comments' => '0',
            ],
            [
              'event_type_id' => '5',
              'title' => 'The Pandemic and Textile Industry. Business parspective',
              'details' => 'What the pandemic means for the Textile Industry and related business. Experts on Pandemic, Textile Industry and business specialist will present the talk. You are cordially invited. Thanks',
              'venue' => null,
              'webinar_url' => 'https://play.google.com/store/apps/details?id=org.jitsi.meet',
              'room_id' => 'webinar.tex2day',
              'password' => '',
              'start_date' => '2020-09-23',
              'end_date' => '2020-09-26',
              'start_time' => '09:00:00',
              'end_time' => '05:00:00 ',
              'contact_phone_no' => '+886-2-26596000',
              'contact_email' => 'akai@chanchao.com.tw',
              'logo' => 'over-img.jpg',
              'banner' => 'cover-img.jpg',
              'total_flag' => '0',
              'is_featured' => '0',
              'is_public' => '1',
              'status' => '0',
              'total_views' => '1',
              'total_likes' => '10',
              'total_comments' => '0',              
            ],
            [
              'event_type_id' => '5',
              'title' => 'How to overcome the impact of CORONA Pandemic in textile industry',
              'details' => 'The reality, impact and the practical steps essential to overcome the CORONA pandemic in textile industry will be discussed on the webinar. Please join. Thanks',
              'venue' => null,
              'webinar_url' => 'https://play.google.com/store/apps/details?id=us.zoom.videomeetings',
              'room_id' => '209 014 2343',
              'password' => 'pass.webinar',
              'start_date' => '2020-09-23',
              'end_date' => '2020-09-26',
              'start_time' => '09:00:00',
              'end_time' => '05:00:00 ',
              'contact_phone_no' => '+886-2-26596000',
              'contact_email' => 'akai@chanchao.com.tw',
              'logo' => 'over-img.jpg',
              'banner' => 'cover-img.jpg',
              'total_flag' => '0',
              'is_featured' => '0',
              'is_public' => '0',
              'status' => '0',
              'total_views' => '1',
              'total_likes' => '10',
              'total_comments' => '0'              
            ],
        ]);
    }
}
