<?php

use Illuminate\Database\Seeder;

class JobsTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        DB::table('jobs')->insert([
            [
              'job_type_id' => '10',
              'job_category_id' => '1',
              'title' => 'Laravel Developer',
              'organization_id' => '1',
              'job_location' => 'Lotus Lounge, Uttara Club, House – 6, Road – 11, Sector – 1',
              'total_vacancy' => '1',
              'application_deadline' => '2020-08-07',
              'salary_range' => '35000tk/monthly',
              'minimum_experience' => '3',
              'maximum_experience' => '5',
              'minimum_age' => '24',
              'maximum_age' => '35',
              'preferred_gender' => '10',
              'responsibilities' => 'In a world where people are struggling every moment to sustain in the current status they are living, the fashion and apparel industry, on which millions of peoples are directly dependent have some responsibilities to the society and its’ elements. Stakeholders like the governments, brands and buyers, consumer right protectors, labor right protectors, community right protectors, trade associations, financial institutions and the factories have their own perspective of sustainability. A holistic approach towards sustainability is needed considering all counterparts and stakeholders to put some real positive impact on businesses, people and planet. Factories being the core and one of the most impactful stakeholders in the value chain need to take systematic approach for implementing sustainability.',
              'requirements' => 'Laravel Framework',
              'other_benefits' => 'Mobile Bill',
              'total_flag' => '0',
              'is_featured' => '0',
              'status' => '20',
              'total_views' => '1',
              'total_applicants' => '0',
              'total_comments' => '0',
              'created_at' => '2020-03-21',
            ],
            [
              'job_type_id' => '1',
              'job_category_id' => '1',
              'title' => 'Software Engineer',
              'organization_id' => '1',
              'job_location' => 'Lotus Lounge, Uttara Club, House – 6, Road – 11, Sector – 1',
              'total_vacancy' => '3',
              'application_deadline' => '2020-06-02',
              'salary_range' => '50000tk/monthly',
              'minimum_experience' => '3',
              'maximum_experience' => '5',
              'minimum_age' => '24',
              'maximum_age' => '35',
              'preferred_gender' => '20',
              'responsibilities' => 'Heart of world technical textiles and nonwoven sector will beat at HIGHTEX 2020.',
              'requirements' => 'Laravel Framework and Vuejs',
              'other_benefits' => 'Mobile Bill, lunch',
              'total_flag' => '0',
              'is_featured' => '0',
              'status' => '20',
              'total_views' => '1',
              'total_applicants' => '3',
              'total_comments' => '0',
              'created_at' => '2020-02-01',
            ],
            [
              'job_type_id' => '1',
              'job_category_id' => '2',
              'organization_id' => '4',
              'title' => 'Manager',
              'job_location' => 'Diamond Island Convention & Exhibition Center ,',
              'total_vacancy' => '1',
              'application_deadline' => '2020-08-01',
              'salary_range' => '40000tk/monthly',
              'minimum_experience' => '3',
              'maximum_experience' => '5',
              'minimum_age' => '24',
              'maximum_age' => '35',
              'preferred_gender' => '30',
              'responsibilities' => 'CAMBODIA’S LEADING B2B EVENTS & TRADE SHOW.',
              'requirements' => 'Dotnet Framwork, MVC',
              'other_benefits' => 'Mobile Bill',
              'total_flag' => '0',
              'is_featured' => '0',
              'status' => '20',
              'total_views' => '1',
              'total_applicants' => '0',
              'total_comments' => '0',
              'created_at' => '2020-01-11',
            ],
            [
              'job_type_id' => '20',
              'job_category_id' => '1',
              'title' => 'Web developer',
              'organization_id' => '10',
              'job_location' => 'International Convention City Bashundhara (ICCB',
              'total_vacancy' => '2',
              'application_deadline' => '2020-06-11',
              'salary_range' => '25000tk/monthly',
              'minimum_experience' => '3',
              'maximum_experience' => '5',
              'minimum_age' => '24',
              'maximum_age' => '35',
              'preferred_gender' => '10',
              'responsibilities' => 'Information, Inspirations and Opportunities.Cambodia Intl Textile & Apparel Accessories Exhibition',
              'requirements' => 'PHP, Python, C#',
              'other_benefits' => 'Mobile Bill, lunch',
              'total_flag' => '0',
              'is_featured' => '0',
              'status' => '20',
              'total_views' => '1',
              'total_applicants' => '0',
              'total_comments' => '0',
              'created_at' => '2020-06-11',
            ],
            [
              'job_type_id' => '10',
              'job_category_id' => '2',
              'title' => 'Sale and Marketing',
              'organization_id' => '15',
              'job_location' => ' International Convention City Bashundhara (ICCB)',
              'total_vacancy' => '5',
              'application_deadline' => '2020-12-18',
              'salary_range' => '30000tk/monthly',
              'minimum_experience' => '3',
              'maximum_experience' => '5',
              'minimum_age' => '24',
              'maximum_age' => '35',
              'preferred_gender' => '30',
              'responsibilities' => 'Information, Inspirations and Opportunities.',
              'requirements' => 'Ms office Expert',
              'other_benefits' => 'Mobile Bill,unlimited Coffee',
              'total_flag' => '0',
              'is_featured' => '0',
              'status' => '20',
              'total_views' => '1',
              'total_applicants' => '0',
              'total_comments' => '0',
              'created_at' => '2020-02-11',
            ],
            [
              'job_type_id' => '1',
              'job_category_id' => '3',
              'title' => 'Manager',
              'organization_id' => '20',
              'job_location' => 'Saigon Exhibition & Conference Center (SECC) (799 Nguyen Van Linh Parkway, Tan Phu Ward, District 7, Ho Chi Minh City, Vietnam)',
              'total_vacancy' => '10',
              'application_deadline' => '2020-09-23',
              'salary_range' => '20000tk/monthly',
              'minimum_experience' => '3',
              'maximum_experience' => '5',
              'minimum_age' => '24',
              'maximum_age' => '35',
              'preferred_gender' => '30',
              'responsibilities' => 'The only dedicated industry specific international trade show for Plastics, Printing & Packaging Industry in Myanmar.The Best sourcing hub in Myanmar for Electrical, Electronics & Electric Power Equipment and related Trade Fair',
              'requirements' => 'HTML, CSS, JavaScript',
              'other_benefits' => 'Mobile Bill, lunch',
              'total_flag' => '0',
              'is_featured' => '0',
              'status' => '20',
              'total_views' => '1',
              'total_applicants' => '0',
              'total_comments' => '0',
              'created_at' => '2020-03-11',
            ],
        ]);
    }
}
